// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","redirect":"/chat/knowledge","parentId":"1","id":"2"},"3":{"path":"/chat/knowledge","parentId":"1","id":"3"},"4":{"path":"/chat/agent","parentId":"1","id":"4"},"5":{"path":"/chat/requirement-dev","parentId":"1","id":"5"},"6":{"path":"/chat/human-review","parentId":"1","id":"6"},"7":{"path":"/knowledge/upload","parentId":"1","id":"7"},"8":{"path":"/knowledge/bases","parentId":"1","id":"8"},"9":{"path":"/agent-hub/skills","parentId":"1","id":"9"},"10":{"path":"/agent-hub/agents","parentId":"1","id":"10"},"11":{"path":"/agent-hub/tools","parentId":"1","id":"11"},"12":{"path":"/agent-hub/mcp","parentId":"1","id":"12"},"13":{"path":"/settings","parentId":"1","id":"13"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout__index" */'@/layouts/BasicLayout/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__chat__knowledge__index" */'@/pages/chat/knowledge/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__chat__agent__index" */'@/pages/chat/agent/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__chat__requirement-dev__index" */'@/pages/chat/requirement-dev/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__chat__human-review__index" */'@/pages/chat/human-review/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__knowledge__upload__index" */'@/pages/knowledge/upload/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__knowledge__bases__index" */'@/pages/knowledge/bases/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__agent-hub__skills__index" */'@/pages/agent-hub/skills/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__agent-hub__agents__index" */'@/pages/agent-hub/agents/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__agent-hub__tools__index" */'@/pages/agent-hub/tools/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__agent-hub__mcp__index" */'@/pages/agent-hub/mcp/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__settings__index" */'@/pages/settings/index.tsx')),
},
  };
}
